--DDL - CRIAR DB
CREATE DATABASE Exercicio_1_4

USE Exercicio_1_4

--CRIAR TABELAS
CREATE TABLE Artista
(
	IdArtista INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL,
);

CREATE TABLE Estilo
(
	IdEstilo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL,
);

CREATE TABLE Permissao
(
	IdPermissao INT PRIMARY KEY IDENTITY,
	Cargo VARCHAR(20) NOT NULL,
);

CREATE TABLE Usuario
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	IdPermissao INT FOREIGN KEY REFERENCES Permissao(IdPermissao),
	Nome VARCHAR(20) NOT NULL,
	Email VARCHAR(20) NOT NULL UNIQUE,
	Senha VARCHAR(20) NOT NULL,
);

CREATE TABLE Album
(
	IdAlbum INT PRIMARY KEY IDENTITY,
	IdArtista INT FOREIGN KEY REFERENCES Artista(IdArtista),
	IdEstilo INT FOREIGN KEY REFERENCES Estilo(IdEstilo),
	Titulo VARCHAR(20) NOT NULL,
	Ativo VARCHAR(3) NOT NULL,
	Duracao INT NOT NULL,
	Lancamento DATE NOT NULL,
	Localizacao VARCHAR(20) NOT NULL,
);


SELECT * FROM Artista
SELECT * FROM Estilo
SELECT * FROM Permissao
SELECT * FROM Usuario
SELECT * FROM Album